package com.example.crypto.helper

class Constants {

    companion object {

        //api key generated by coinmarket site by my user
        const val API_KEY_VALUE: String = "aec338c7-932e-464d-be06-a062bf0b4e87"
        const val API_KEY: String = "X-CMC_PRO_API_KEY"

        const val HEADER_KEY: String = "Accept"
        const val HEADER_KEY_VALUE: String = "application/json"
    }
}