package com.example.crypto.helper

import com.example.crypto.model.enums.CryptoType
import com.example.crypto.model.enums.SortType
import com.example.crypto.model.enums.TagType
import java.util.*

class Constants {

    companion object {

        //api key generated by coinmarket site by my user
        const val API_KEY_VALUE: String = "aec338c7-932e-464d-be06-a062bf0b4e87"
        const val API_KEY: String = "X-CMC_PRO_API_KEY"

        const val HEADER_KEY: String = "Accept"
        const val HEADER_KEY_VALUE: String = "application/json"

        //timeout amount of api calls
        const val  TIMEOUT_VALUE: Long = 30

        //amount of cryptocurrencies items loading in each page
        const val  PAGE_SIZE: String = "20"


        var public_sort_text: String = SortType.MARKET_CAP.toString().toLowerCase(Locale.ROOT)
        var public_tag_text: String = TagType.ALL.toString().toLowerCase(Locale.ROOT)
        var public_crypto_text: String = CryptoType.ALL.toString().toLowerCase(Locale.ROOT)
    }
}